- name: Setup CI/CD Workshop Class
  hosts: 127.0.0.1
  connection: local

  vars:
    students_start: 5
    students_end: 6

  tasks:
  - name: Add Registry to Anchore
    shell: |
      anchore-cli --u admin --p foobar --url http://anchore-student-{{ item }}-cicd.apps.ocp-nonprod-01.kee.vizuri.com registry add --insecure registry.kee.vizuri.com student-{{ item }} workshop1!
    retries: 20
    delay: 10
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"


