- name: Setup CI/CD Workshop Class
  hosts: 127.0.0.1
  connection: local

  vars:
    gogs_url: "gogs.apps.ocpws.kee.vizuri.com"
    access_token: "6333b54ffc4ec28da977ddad0a9e017fce4e0c72"
    repo_name: "customer-service"
    students_start: 0
    students_end: 0

  tasks:
  - name: Create Gogs User
    uri:
      url: "http://{{ gogs_url }}/api/v1/admin/users"
      method: POST
      body_format: json
      headers: 
        Content-Type: "application/json"
        Authorization: "token {{ access_token }}"
      status_code: 201
      timeout: 10
      body: "{\"source_id\": 1, \"login_name\": \"student-{{ item }}\", \"username\": \"student-{{ item }}\", \"email\": \"student-{{ item }}@vizuri.com\" }"
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"


  - name: Create Customer Service Repo
    uri:
      url: "http://{{ gogs_url }}/api/v1/admin/users/student-{{ item }}/repos"
      method: POST
      body_format: json
      headers: 
        Content-Type: "application/json"
        Authorization: "token {{ access_token }}"
      status_code: 201
      timeout: 10
      body: "{\"Name\": \"{{ repo_name }}\", \"Description\": \"{{ repo_name }}\", \"private\": false }"
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"

  - name: Populate Customer Service Repo
    shell: |
      #git clone git@github.com:Vizuri/openshift-cicd-customer-service.git
      git clone https://github.com/Vizuri/openshift-cicd-customer-service.git
      cd openshift-cicd-customer-service
      git remote add gogs http://student-{{ item }}:workshop1!@{{ gogs_url }}/student-{{ item }}/customer-service.git
      git checkout -b develop origin/develop
      git push gogs develop
      cd ..
      rm -fr openshift-cicd-customer-service
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"

