- name: Setup CI/CD Workshop Class
  hosts: 127.0.0.1
  connection: local

  vars:
    gogs_url: "http://gogs.apps.ocpws.kee.vizuri.com"
    access_token: "63a4c301714053cb5763172e87120c4bb4a9b2b5"
    repo_name: "customer-service"
    students_start: 50 
    students_end: 55 

  tasks:
#  - name: Delete LDAP User
#    ldap_entry:
#      bind_dn: cn=Directory Manager
#      bind_pw: P@ssw0rd
#      server_uri: ldap://directory.kee.vizuri.com
#      dn: "uid=student-{{ item }},ou=people,dc=vizuri,dc=com"
#      state: absent
#    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"


  - name: Delete Gogs User Repo
    uri:
      url: "{{ gogs_url }}/api/v1/repos/student-{{ item }}/{{ repo_name }}"
      method: DELETE
      headers: 
        Authorization: "token {{ access_token }}"
      status_code: 204
      timeout: 10
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"


  - name: Delete Gogs User
    uri:
      url: "{{ gogs_url }}/api/v1/admin/users/student-{{ item }}"
      method: DELETE
      headers: 
        Authorization: "token {{ access_token }}"
      status_code: 204
      timeout: 10
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"

